theme: jekyll-theme-slate
title: Honeyman's Violin Tutor Resource
description: A compilation of performances by various violinists of the pieces from The Young Violinist's Tutor and Duet Book by W. C. Honeyman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
google_analytics: <meta name="google-site-verification" content="rCiKpHkKQTxgbi3Zn0y6VIdNVQ83VDkr6hY0OcZu-K0" />
